package be.renaud11232.bluemapmobs.fabric;

import be.renaud11232.bluemapentities.EntityConverter;
import be.renaud11232.bluemapmobs.fabric.entity.*;
import net.minecraft.world.entity.Mob;
import net.minecraft.world.entity.ambient.Bat;
import net.minecraft.world.entity.animal.allay.Allay;
import net.minecraft.world.entity.animal.armadillo.Armadillo;
import net.minecraft.world.entity.animal.axolotl.Axolotl;
import net.minecraft.world.entity.animal.bee.Bee;
import net.minecraft.world.entity.animal.camel.Camel;
import net.minecraft.world.entity.animal.camel.CamelHusk;
import net.minecraft.world.entity.animal.chicken.Chicken;
import net.minecraft.world.entity.animal.cow.Cow;
import net.minecraft.world.entity.animal.cow.MushroomCow;
import net.minecraft.world.entity.animal.dolphin.Dolphin;
import net.minecraft.world.entity.animal.equine.*;
import net.minecraft.world.entity.animal.feline.Cat;
import net.minecraft.world.entity.animal.feline.Ocelot;
import net.minecraft.world.entity.animal.fish.Cod;
import net.minecraft.world.entity.animal.fish.Pufferfish;
import net.minecraft.world.entity.animal.fish.Salmon;
import net.minecraft.world.entity.animal.fish.TropicalFish;
import net.minecraft.world.entity.animal.fox.Fox;
import net.minecraft.world.entity.animal.frog.Frog;
import net.minecraft.world.entity.animal.frog.Tadpole;
import net.minecraft.world.entity.animal.goat.Goat;
import net.minecraft.world.entity.animal.golem.CopperGolem;
import net.minecraft.world.entity.animal.golem.IronGolem;
import net.minecraft.world.entity.animal.golem.SnowGolem;
import net.minecraft.world.entity.animal.happyghast.HappyGhast;
import net.minecraft.world.entity.animal.nautilus.Nautilus;
import net.minecraft.world.entity.animal.nautilus.ZombieNautilus;
import net.minecraft.world.entity.animal.panda.Panda;
import net.minecraft.world.entity.animal.parrot.Parrot;
import net.minecraft.world.entity.animal.pig.Pig;
import net.minecraft.world.entity.animal.polarbear.PolarBear;
import net.minecraft.world.entity.animal.rabbit.Rabbit;
import net.minecraft.world.entity.animal.sheep.Sheep;
import net.minecraft.world.entity.animal.sniffer.Sniffer;
import net.minecraft.world.entity.animal.squid.GlowSquid;
import net.minecraft.world.entity.animal.squid.Squid;
import net.minecraft.world.entity.animal.turtle.Turtle;
import net.minecraft.world.entity.animal.wolf.Wolf;
import net.minecraft.world.entity.boss.enderdragon.EnderDragon;
import net.minecraft.world.entity.boss.wither.WitherBoss;
import net.minecraft.world.entity.monster.*;
import net.minecraft.world.entity.monster.breeze.Breeze;
import net.minecraft.world.entity.monster.creaking.Creaking;
import net.minecraft.world.entity.monster.cubemob.MagmaCube;
import net.minecraft.world.entity.monster.cubemob.Slime;
import net.minecraft.world.entity.monster.cubemob.SulfurCube;
import net.minecraft.world.entity.monster.hoglin.Hoglin;
import net.minecraft.world.entity.monster.illager.Evoker;
import net.minecraft.world.entity.monster.illager.Illusioner;
import net.minecraft.world.entity.monster.illager.Pillager;
import net.minecraft.world.entity.monster.illager.Vindicator;
import net.minecraft.world.entity.monster.piglin.Piglin;
import net.minecraft.world.entity.monster.piglin.PiglinBrute;
import net.minecraft.world.entity.monster.skeleton.*;
import net.minecraft.world.entity.monster.spider.CaveSpider;
import net.minecraft.world.entity.monster.spider.Spider;
import net.minecraft.world.entity.monster.warden.Warden;
import net.minecraft.world.entity.monster.zombie.*;
import net.minecraft.world.entity.npc.villager.Villager;
import net.minecraft.world.entity.npc.wanderingtrader.WanderingTrader;

public class FabricMobConverter implements EntityConverter<Mob, be.renaud11232.bluemapmobs.entity.Mob> {
    @Override
    public be.renaud11232.bluemapmobs.entity.Mob convert(Mob mob) {
        return switch (mob) {
            case Allay allay -> new FabricAllay(allay);
            case Armadillo armadillo -> new FabricArmadillo(armadillo);
            case Axolotl axolotl -> new FabricAxolotl(axolotl);
            case Bat bat -> new FabricBat(bat);
            case Bee bee -> new FabricBee(bee);
            case Blaze blaze -> new FabricBlaze(blaze);
            case Bogged bogged -> new FabricBogged(bogged);
            case Breeze breeze -> new FabricBreeze(breeze);
            case CamelHusk camelHusk -> new FabricCamelHusk(camelHusk);
            case Camel camel -> new FabricCamel(camel);
            case Cat cat -> new FabricCat(cat);
            case CaveSpider caveSpider -> new FabricCaveSpider(caveSpider);
            case Chicken chicken -> new FabricChicken(chicken);
            case Cod cod -> new FabricCod(cod);
            case CopperGolem copperGolem -> new FabricCopperGolem(copperGolem);
            case Cow cow -> new FabricCow(cow);
            case Creaking creaking -> new FabricCreaking(creaking);
            case Creeper creeper -> new FabricCreeper(creeper);
            case Dolphin dolphin -> new FabricDolphin(dolphin);
            case Donkey donkey -> new FabricDonkey(donkey);
            case Drowned drowned -> new FabricDrowned(drowned);
            case ElderGuardian elderGuardian -> new FabricElderGuardian(elderGuardian);
            case EnderMan enderman -> new FabricEnderman(enderman);
            case Endermite endermite -> new FabricEndermite(endermite);
            case EnderDragon enderDragon -> new FabricEnderDragon(enderDragon);
            case Evoker evoker -> new FabricEvoker(evoker);
            case Fox fox -> new FabricFox(fox);
            case Frog frog -> new FabricFrog(frog);
            case Ghast ghast -> new FabricGhast(ghast);
            case Giant giant -> new FabricGiant(giant);
            case GlowSquid glowSquid -> new FabricGlowSquid(glowSquid);
            case Goat goat -> new FabricGoat(goat);
            case Guardian guardian -> new FabricGuardian(guardian);
            case HappyGhast happyGhast -> new FabricHappyGhast(happyGhast);
            case Hoglin hoglin -> new FabricHoglin(hoglin);
            case Horse horse -> new FabricHorse(horse);
            case Husk husk -> new FabricHusk(husk);
            case Illusioner illusioner -> new FabricIllusioner(illusioner);
            case IronGolem ironGolem -> new FabricIronGolem(ironGolem);
            case TraderLlama traderLlama -> new FabricTraderLlama(traderLlama);
            case Llama llama -> new FabricLlama(llama);
            case MagmaCube magmaCube -> new FabricMagmaCube(magmaCube);
            case Mule mule -> new FabricMule(mule);
            case MushroomCow mushroomCow -> new FabricMushroomCow(mushroomCow);
            case Nautilus nautilus -> new FabricNautilus(nautilus);
            case Ocelot ocelot -> new FabricOcelot(ocelot);
            case Panda panda -> new FabricPanda(panda);
            case Parched parched -> new FabricParched(parched);
            case Parrot parrot -> new FabricParrot(parrot);
            case Phantom phantom -> new FabricPhantom(phantom);
            case Pig pig -> new FabricPig(pig);
            case Piglin piglin -> new FabricPiglin(piglin);
            case PiglinBrute piglinBrute -> new FabricPiglinBrute(piglinBrute);
            case Pillager pillager -> new FabricPillager(pillager);
            case PolarBear polarBear -> new FabricPolarBear(polarBear);
            case Pufferfish pufferfish -> new FabricPufferFish(pufferfish);
            case Rabbit rabbit -> new FabricRabbit(rabbit);
            case Ravager ravager -> new FabricRavager(ravager);
            case Salmon salmon -> new FabricSalmon(salmon);
            case Sheep sheep -> new FabricSheep(sheep);
            case Shulker shulker -> new FabricShulker(shulker);
            case Silverfish silverfish -> new FabricSilverfish(silverfish);
            case Skeleton skeleton -> new FabricSkeleton(skeleton);
            case SkeletonHorse skeletonHorse -> new FabricSkeletonHorse(skeletonHorse);
            case Slime slime -> new FabricSlime(slime);
            case Sniffer sniffer -> new FabricSniffer(sniffer);
            case SnowGolem snowGolem -> new FabricSnowman(snowGolem);
            case Spider spider -> new FabricSpider(spider);
            case Squid squid -> new FabricSquid(squid);
            case Stray stray -> new FabricStray(stray);
            case Strider strider -> new FabricStrider(strider);
            case SulfurCube sulfurCube -> new FabricSulfurCube(sulfurCube);
            case Tadpole tadpole -> new FabricTadpole(tadpole);
            case TropicalFish tropicalFish -> new FabricTropicalFish(tropicalFish);
            case Turtle turtle -> new FabricTurtle(turtle);
            case Vex vex -> new FabricVex(vex);
            case Villager villager -> new FabricVillager(villager);
            case Vindicator vindicator -> new FabricVindicator(vindicator);
            case WanderingTrader wanderingTrader -> new FabricWanderingTrader(wanderingTrader);
            case Warden warden -> new FabricWarden(warden);
            case Witch witch -> new FabricWitch(witch);
            case WitherBoss witherBoss -> new FabricWither(witherBoss);
            case WitherSkeleton witherSkeleton -> new FabricWitherSkeleton(witherSkeleton);
            case Wolf wolf -> new FabricWolf(wolf);
            case Zoglin zoglin -> new FabricZoglin(zoglin);
            case ZombieVillager zombieVillager -> new FabricZombieVillager(zombieVillager);
            case ZombifiedPiglin zombifiedPiglin -> new FabricZombifiedPiglin(zombifiedPiglin);
            case Zombie zombie -> new FabricZombie(zombie);
            case ZombieHorse zombieHorse -> new FabricZombieHorse(zombieHorse);
            case ZombieNautilus zombieNautilus -> new FabricZombieNautilus(zombieNautilus);
            default -> new FabricUnknownMob(mob);
        };
    }
}
