org.gradle.configuration-cache=false

group=be.renaud11232
version=2.1.0-SNAPSHOT
java-version=25
bukkit-api-version=26.2
minecraft-api-version=26.2
website=https://github.com/Renaud11232/BlueMapMobs

bluemap-citizens-description=Plugin adding Citizens NPCs markers on your BlueMap maps
bluemap-mobs-description=Plugin adding mob markers on your BlueMap maps
bluemap-others-description=Plugin adding markers on your BlueMap maps for other entities than mobs and vehicles
bluemap-vehicles-description=Plugin adding vehicle markers on your BlueMap maps