rootProject.name = "bluemap-entity-markers"

include("bluemap-entity-markers-common")
include("bluemap-entity-markers-bukkit-common")
include("bluemap-entity-markers-fabric-common")
include("bluemap-citizens-markers-bukkit")
include("bluemap-vehicle-markers-common")
include("bluemap-vehicle-markers-bukkit")
include("bluemap-vehicle-markers-fabric")
include("bluemap-mob-markers-common")
include("bluemap-mob-markers-bukkit-common")
include("bluemap-mob-markers-spigot")
include("bluemap-mob-markers-paper")
include("bluemap-mob-markers-fabric")
include("bluemap-other-markers-common")
include("bluemap-other-markers-bukkit-common")
include("bluemap-other-markers-spigot")
include("bluemap-other-markers-paper")
include("bluemap-other-markers-fabric")
include("bluemap-entity-markers-icon-generator")