general:
  # Number of ticks between updates
  refresh_rate: 200
  # Hide markers if they are in light levels under the specified value
  # Both values have to be below the threshold fot the marker to be hidden
  # 0 = Full shadow (doesn't hide the marker)
  # 16 = Full block light
  # 15 = Full sky light
  minimum_block_light: 4
  minimum_sky_light: 1

marker_sets:
  mobs:
    key: "bluemapmobs-mobs"
    label: "Mobs"
    toggleable: true
    default_hidden: true
    max_distance: 1000
    display:

  vehicles:
    key: "bluemapmobs-vehicles"
    label: "Vehicles"
    toggleable: true
    default_hidden: true
    max_distance: 1000
    display:
      chest_boat: true
      boat: true
      command_minecart: true
      explosive_minecart: true
      hopper_minecart: true
      powered_minecart: true
      rideable_minecart: true
      spawner_minecart: true
      storage_minecart: true