name: BlueMapMobs
version: '${project.version}'
main: be.renaud11232.bluemapmobs.BlueMapMobs
api-version: '1.21.9'
depend:
  - BlueMap
softdepend:
  - Citizens
authors:
  - Renaud11232
description: '${project.description}'
website: '${project.url}'
