name: BlueMapMobs
version: '${project.version}'
main: be.renaud11232.bluemapmobs.BlueMapMobs
api-version: '1.21.5'
depend:
  - BlueMap
authors:
  - Renaud11232
description: '${project.description}'
website: '${project.url}'
