package be.renaud11232.bluemapmobmarkers.markerbuilder;

import be.renaud11232.bluemapentitymarkers.configuration.Configuration;
import be.renaud11232.bluemapentitymarkers.entity.UnknownEntity;
import be.renaud11232.bluemapentitymarkers.markerbuilder.EmptyMarkerBuilder;
import be.renaud11232.bluemapentitymarkers.markerbuilder.SimpleMarkerBuilder;
import be.renaud11232.bluemapmobmarkers.entity.*;
import de.bluecolored.bluemap.api.BlueMapAPI;

public class MobsMarkerBuilder extends SimpleMarkerBuilder<Mob> {
    public MobsMarkerBuilder(BlueMapAPI api, Configuration configuration) {
        super(api, configuration);
        register(Allay.class, new AllayMarkerBuilder(getAPI(), getConfiguration()));
        register(Armadillo.class, new ArmadilloMarkerBuilder(getAPI(), getConfiguration()));
        register(Axolotl.class, new AxolotlMarkerBuilder(getAPI(), getConfiguration()));
        register(Bat.class, new BatMarkerBuilder(getAPI(), getConfiguration()));
        register(Bee.class, new BeeMarkerBuilder(getAPI(), getConfiguration()));
        register(Blaze.class, new BlazeMarkerBuilder(getAPI(), getConfiguration()));
        register(Bogged.class, new BoggedMarkerBuilder(getAPI(), getConfiguration()));
        register(Breeze.class, new BreezeMarkerBuilder(getAPI(), getConfiguration()));
        register(Camel.class, new CamelMarkerBuilder(getAPI(), getConfiguration()));
        register(CamelHusk.class, new CamelHuskMarkerBuilder(getAPI(), getConfiguration()));
        register(Cat.class, new CatMarkerBuilder(getAPI(), getConfiguration()));
        register(CaveSpider.class, new CaveSpiderMarkerBuilder(getAPI(), getConfiguration()));
        register(Chicken.class, new ChickenMarkerBuilder(getAPI(), getConfiguration()));
        register(Cod.class, new CodMarkerBuilder(getAPI(), getConfiguration()));
        register(CopperGolem.class, new CopperGolemMarkerBuilder(getAPI(), getConfiguration()));
        register(Cow.class, new CowMarkerBuilder(getAPI(), getConfiguration()));
        register(Creaking.class, new CreakingMarkerBuilder(getAPI(), getConfiguration()));
        register(Creeper.class, new CreeperMarkerBuilder(getAPI(), getConfiguration()));
        register(Dolphin.class, new DolphinMarkerBuilder(getAPI(), getConfiguration()));
        register(Donkey.class, new DonkeyMarkerBuilder(getAPI(), getConfiguration()));
        register(Drowned.class, new DrownedMarkerBuilder(getAPI(), getConfiguration()));
        register(ElderGuardian.class, new ElderGuardianMarkerBuilder(getAPI(), getConfiguration()));
        register(Enderman.class, new EndermanMarkerBuilder(getAPI(), getConfiguration()));
        register(Endermite.class, new EndermiteMarkerBuilder(getAPI(), getConfiguration()));
        register(EnderDragon.class, new EnderDragonMarkerBuilder(getAPI(), getConfiguration()));
        register(Evoker.class, new EvokerMarkerBuilder(getAPI(), getConfiguration()));
        register(Fox.class, new FoxMarkerBuilder(getAPI(), getConfiguration()));
        register(Frog.class, new FrogMarkerBuilder(getAPI(), getConfiguration()));
        register(Ghast.class, new GhastMarkerBuilder(getAPI(), getConfiguration()));
        register(Giant.class, new GiantMarkerBuilder(getAPI(), getConfiguration()));
        register(GlowSquid.class, new GlowSquidMarkerBuilder(getAPI(), getConfiguration()));
        register(Goat.class, new GoatMarkerBuilder(getAPI(), getConfiguration()));
        register(Guardian.class, new GuardianMarkerBuilder(getAPI(), getConfiguration()));
        register(HappyGhast.class, new HappyGhastMarkerBuilder(getAPI(), getConfiguration()));
        register(Hoglin.class, new HoglinMarkerBuilder(getAPI(), getConfiguration()));
        register(Horse.class, new HorseMarkerBuilder(getAPI(), getConfiguration()));
        register(Husk.class, new HuskMarkerBuilder(getAPI(), getConfiguration()));
        register(Illusioner.class, new IllusionerMarkerBuilder(getAPI(), getConfiguration()));
        register(IronGolem.class, new IronGolemMarkerBuilder(getAPI(), getConfiguration()));
        register(Llama.class, new LlamaMarkerBuilder(getAPI(), getConfiguration()));
        register(MagmaCube.class, new MagmaCubeMarkerBuilder(getAPI(), getConfiguration()));
        register(Mule.class, new MuleMarkerBuilder(getAPI(), getConfiguration()));
        register(MushroomCow.class, new MushroomCowMarkerBuilder(getAPI(), getConfiguration()));
        register(Nautilus.class, new NautilusMarkerBuilder(getAPI(), getConfiguration()));
        register(Ocelot.class, new OcelotMarkerBuilder(getAPI(), getConfiguration()));
        register(Panda.class, new PandaMarkerBuilder(getAPI(), getConfiguration()));
        register(Parched.class, new ParchedMarkerBuilder(getAPI(), getConfiguration()));
        register(Parrot.class, new ParrotMarkerBuilder(getAPI(), getConfiguration()));
        register(Phantom.class, new PhantomMarkerBuilder(getAPI(), getConfiguration()));
        register(Pig.class, new PigMarkerBuilder(getAPI(), getConfiguration()));
        register(Piglin.class, new PiglinMarkerBuilder(getAPI(), getConfiguration()));
        register(PiglinBrute.class, new PiglinBruteMarkerBuilder(getAPI(), getConfiguration()));
        register(Pillager.class, new PillagerMarkerBuilder(getAPI(), getConfiguration()));
        register(PolarBear.class, new PolarBearMarkerBuilder(getAPI(), getConfiguration()));
        register(PufferFish.class, new PufferFishMarkerBuilder(getAPI(), getConfiguration()));
        register(Rabbit.class, new RabbitMarkerBuilder(getAPI(), getConfiguration()));
        register(Ravager.class, new RavagerMarkerBuilder(getAPI(), getConfiguration()));
        register(Salmon.class, new SalmonMarkerBuilder(getAPI(), getConfiguration()));
        register(Sheep.class, new SheepMarkerBuilder(getAPI(), getConfiguration()));
        register(Shulker.class, new ShulkerMarkerBuilder(getAPI(), getConfiguration()));
        register(Silverfish.class, new SilverfishMarkerBuilder(getAPI(), getConfiguration()));
        register(Skeleton.class, new SkeletonMarkerBuilder(getAPI(), getConfiguration()));
        register(SkeletonHorse.class, new SkeletonHorseMarkerBuilder(getAPI(), getConfiguration()));
        register(Slime.class, new SlimeMarkerBuilder(getAPI(), getConfiguration()));
        register(Sniffer.class, new SnifferMarkerBuilder(getAPI(), getConfiguration()));
        register(Snowman.class, new SnowmanMarkerBuilder(getAPI(), getConfiguration()));
        register(Spider.class, new SpiderMarkerBuilder(getAPI(), getConfiguration()));
        register(Squid.class, new SquidMarkerBuilder(getAPI(), getConfiguration()));
        register(Stray.class, new StrayMarkerBuilder(getAPI(), getConfiguration()));
        register(Strider.class, new StriderMarkerBuilder(getAPI(), getConfiguration()));
        register(SulfurCube.class, new SulfurCubeMarkerBuilder(getAPI(), getConfiguration()));
        register(Tadpole.class, new TadpoleMarkerBuilder(getAPI(), getConfiguration()));
        register(TraderLlama.class, new TraderLlamaMarkerBuilder(getAPI(), getConfiguration()));
        register(TropicalFish.class, new TropicalFishMarkerBuilder(getAPI(), getConfiguration()));
        register(Turtle.class, new TurtleMarkerBuilder(getAPI(), getConfiguration()));
        register(Vex.class, new VexMarkerBuilder(getAPI(), getConfiguration()));
        register(Villager.class, new VillagerMarkerBuilder(getAPI(), getConfiguration()));
        register(Vindicator.class, new VindicatorMarkerBuilder(getAPI(), getConfiguration()));
        register(WanderingTrader.class, new WanderingTraderMarkerBuilder(getAPI(), getConfiguration()));
        register(Warden.class, new WardenMarkerBuilder(getAPI(), getConfiguration()));
        register(Witch.class, new WitchMarkerBuilder(getAPI(), getConfiguration()));
        register(Wither.class, new WitherMarkerBuilder(getAPI(), getConfiguration()));
        register(WitherSkeleton.class, new WitherSkeletonMarkerBuilder(getAPI(), getConfiguration()));
        register(Wolf.class, new WolfMarkerBuilder(getAPI(), getConfiguration()));
        register(Zoglin.class, new ZoglinMarkerBuilder(getAPI(), getConfiguration()));
        register(Zombie.class, new ZombieMarkerBuilder(getAPI(), getConfiguration()));
        register(ZombieHorse.class, new ZombieHorseMarkerBuilder(getAPI(), getConfiguration()));
        register(ZombieNautilus.class, new ZombieNautilusMarkerBuilder(getAPI(), getConfiguration()));
        register(ZombieVillager.class, new ZombieVillagerMarkerBuilder(getAPI(), getConfiguration()));
        register(ZombifiedPiglin.class, new ZombifiedPiglinMarkerBuilder(getAPI(), getConfiguration()));

        register(UnknownEntity.class, new EmptyMarkerBuilder<>());
    }
}
