name: BlueMapMobMarkers
version: '${version}'
main: be.renaud11232.bluemapmobmarkers.spigot.SpigotBlueMapMobMarkersPlugin
api-version: '${apiVersion}'
depend:
  - BlueMap
authors:
  - Renaud11232
description: '${description}'
website: '${website}'
