package be.renaud11232.bluemapmobs;

import be.renaud11232.bluemapmobs.entity.TropicalFish;

public class MobsStyleClass {
    public static final String FLIP = "bluemapmobs-flip";
    public static final String BEE = "bluemapmobs-bee";
    public static final String BEE_ANGRY = "bluemapmobs-bee-angry";
    public static final String BEE_BABY = "bluemapmobs-bee-baby";
    public static final String BEE_ANGRY_BABY = "bluemapmobs-bee-angry-baby";
    public static final String HAPPY_GHAST = "bluemapmobs-happy-ghast";
    public static final String HORSE_WHITE = "bluemapmobs-horse-white";
    public static final String HORSE_CREAMY = "bluemapmobs-horse-creamy";
    public static final String HORSE_CHESTNUT = "bluemapmobs-horse-chestnut";
    public static final String HORSE_BROWN = "bluemapmobs-horse-brown";
    public static final String HORSE_BLACK = "bluemapmobs-horse-black";
    public static final String HORSE_GRAY = "bluemapmobs-horse-gray";
    public static final String HORSE_DARK_BROWN = "bluemapmobs-horse-dark-brown";
    public static final String HORSE_WHITE_BABY = "bluemapmobs-horse-white-baby";
    public static final String HORSE_CREAMY_BABY = "bluemapmobs-horse-creamy-baby";
    public static final String HORSE_CHESTNUT_BABY = "bluemapmobs-horse-chestnut-baby";
    public static final String HORSE_BROWN_BABY = "bluemapmobs-horse-brown-baby";
    public static final String HORSE_BLACK_BABY = "bluemapmobs-horse-black-baby";
    public static final String HORSE_GRAY_BABY = "bluemapmobs-horse-gray-baby";
    public static final String HORSE_DARK_BROWN_BABY = "bluemapmobs-horse-dark-brown-baby";
    public static final String LLAMA_CREAMY = "bluemapmobs-llama-creamy";
    public static final String LLAMA_WHITE = "bluemapmobs-llama-white";
    public static final String LLAMA_GRAY = "bluemapmobs-llama-gray";
    public static final String LLAMA_BROWN = "bluemapmobs-llama-brown";
    public static final String LLAMA_CREAMY_BABY = "bluemapmobs-llama-creamy-baby";
    public static final String LLAMA_WHITE_BABY = "bluemapmobs-llama-white-baby";
    public static final String LLAMA_GRAY_BABY = "bluemapmobs-llama-gray-baby";
    public static final String LLAMA_BROWN_BABY = "bluemapmobs-llama-brown-baby";
    public static final String SHEEP_WOOL_WHITE = "bluemapmobs-sheep-wool-white";
    public static final String SHEEP_WOOL_ORANGE = "bluemapmobs-sheep-wool-orange";
    public static final String SHEEP_WOOL_MAGENTA = "bluemapmobs-sheep-wool-magenta";
    public static final String SHEEP_WOOL_LIGHT_BLUE = "bluemapmobs-sheep-wool-light-blue";
    public static final String SHEEP_WOOL_YELLOW = "bluemapmobs-sheep-wool-yellow";
    public static final String SHEEP_WOOL_LIME = "bluemapmobs-sheep-wool-lime";
    public static final String SHEEP_WOOL_PINK = "bluemapmobs-sheep-wool-pink";
    public static final String SHEEP_WOOL_GRAY = "bluemapmobs-sheep-wool-gray";
    public static final String SHEEP_WOOL_LIGHT_GRAY = "bluemapmobs-sheep-wool-light-gray";
    public static final String SHEEP_WOOL_CYAN = "bluemapmobs-sheep-wool-cyan";
    public static final String SHEEP_WOOL_PURPLE = "bluemapmobs-sheep-wool-purple";
    public static final String SHEEP_WOOL_BLUE = "bluemapmobs-sheep-wool-blue";
    public static final String SHEEP_WOOL_BROWN = "bluemapmobs-sheep-wool-brown";
    public static final String SHEEP_WOOL_GREEN = "bluemapmobs-sheep-wool-green";
    public static final String SHEEP_WOOL_RED = "bluemapmobs-sheep-wool-red";
    public static final String SHEEP_WOOL_BLACK = "bluemapmobs-sheep-wool-black";
    public static final String SHEEP_JEB = "bluemapmobs-sheep-wool-jeb";
    public static final String SHEEP_WOOL_WHITE_BABY = "bluemapmobs-sheep-wool-white-baby";
    public static final String SHEEP_WOOL_ORANGE_BABY = "bluemapmobs-sheep-wool-orange-baby";
    public static final String SHEEP_WOOL_MAGENTA_BABY = "bluemapmobs-sheep-wool-magenta-baby";
    public static final String SHEEP_WOOL_LIGHT_BLUE_BABY = "bluemapmobs-sheep-wool-light-blue-baby";
    public static final String SHEEP_WOOL_YELLOW_BABY = "bluemapmobs-sheep-wool-yellow-baby";
    public static final String SHEEP_WOOL_LIME_BABY = "bluemapmobs-sheep-wool-lime-baby";
    public static final String SHEEP_WOOL_PINK_BABY = "bluemapmobs-sheep-wool-pink-baby";
    public static final String SHEEP_WOOL_GRAY_BABY = "bluemapmobs-sheep-wool-gray-baby";
    public static final String SHEEP_WOOL_LIGHT_GRAY_BABY = "bluemapmobs-sheep-wool-light-gray-baby";
    public static final String SHEEP_WOOL_CYAN_BABY = "bluemapmobs-sheep-wool-cyan-baby";
    public static final String SHEEP_WOOL_PURPLE_BABY = "bluemapmobs-sheep-wool-purple-baby";
    public static final String SHEEP_WOOL_BLUE_BABY = "bluemapmobs-sheep-wool-blue-baby";
    public static final String SHEEP_WOOL_BROWN_BABY = "bluemapmobs-sheep-wool-brown-baby";
    public static final String SHEEP_WOOL_GREEN_BABY = "bluemapmobs-sheep-wool-green-baby";
    public static final String SHEEP_WOOL_RED_BABY = "bluemapmobs-sheep-wool-red-baby";
    public static final String SHEEP_WOOL_BLACK_BABY = "bluemapmobs-sheep-wool-black-baby";
    public static final String SHEEP_JEB_BABY = "bluemapmobs-sheep-wool-jeb-baby";
    public static String tropicalFishBody(TropicalFish.BodyType bodyType, TropicalFish.Color bodyColor) {
        return String.format("bluemapmobs-tropical-fish-body-%s-%s", bodyType.name().toLowerCase(), bodyColor.name().toLowerCase().replace('_', '-'));
    }
    public static final String VILLAGER = "bluemapmobs-villager";
    public static final String VILLAGER_BABY = "bluemapmobs-villager-baby";
    public static final String ZOMBIE_VILLAGER = "bluemapmobs-zombie-villager";
    public static final String ZOMBIE_VILLAGER_BABY = "bluemapmobs-zombie-villager-baby";
}
