name: BlueMapVehicles
version: '${project.version}'
main: be.renaud11232.bluemapvehicles.bukkit.BukkitBlueMapVehicles
api-version: '${net.minecraft.target.version}'
depend:
  - BlueMapEntities
authors:
  - Renaud11232
description: '${project.description}'
website: '${project.url}'
