name: BlueMapVehicles
version: '${version}'
main: be.renaud11232.bluemapvehicles.bukkit.BukkitBlueMapVehicles
api-version: '${apiVersion}'
depend:
  - BlueMap
authors:
  - Renaud11232
description: '${description}'
website: '${website}'
