package be.renaud11232.bluemapmobs.bukkit;

import be.renaud11232.bluemapentities.EntityConverter;
import be.renaud11232.bluemapmobs.bukkit.entity.*;
import org.bukkit.entity.*;

public abstract class BukkitCommonMobConverter implements EntityConverter<Mob, be.renaud11232.bluemapmobs.entity.Mob> {
    @Override
    public be.renaud11232.bluemapmobs.entity.Mob convert(Mob mob) {
        return switch (mob) {
            case Allay allay -> new BukkitAllay(allay);
            case Armadillo armadillo -> new BukkitArmadillo(armadillo);
            case Axolotl axolotl -> new BukkitAxolotl(axolotl);
            case Bat bat -> new BukkitBat(bat);
            case Bee bee -> new BukkitBee(bee);
            case Blaze blaze -> new BukkitBlaze(blaze);
            case Bogged bogged -> new BukkitBogged(bogged);
            case Breeze breeze -> new BukkitBreeze(breeze);
            case CamelHusk camelHusk -> new BukkitCamelHusk(camelHusk);
            case Camel camel -> new BukkitCamel(camel);
            case Cat cat -> new BukkitCat(cat);
            case CaveSpider caveSpider -> new BukkitCaveSpider(caveSpider);
            case Chicken chicken -> new BukkitChicken(chicken);
            case Cod cod -> new BukkitCod(cod);
            case Cow cow -> new BukkitCow(cow);
            case Creaking creaking -> new BukkitCreaking(creaking);
            case Creeper creeper -> new BukkitCreeper(creeper);
            case Dolphin dolphin -> new BukkitDolphin(dolphin);
            case Donkey donkey -> new BukkitDonkey(donkey);
            case Drowned drowned -> new BukkitDrowned(drowned);
            case ElderGuardian elderGuardian -> new BukkitElderGuardian(elderGuardian);
            case Enderman enderman -> new BukkitEnderman(enderman);
            case Endermite endermite -> new BukkitEndermite(endermite);
            case EnderDragon enderDragon -> new BukkitEnderDragon(enderDragon);
            case Evoker evoker -> new BukkitEvoker(evoker);
            case Fox fox -> new BukkitFox(fox);
            case Frog frog -> new BukkitFrog(frog);
            case Ghast ghast -> new BukkitGhast(ghast);
            case Giant giant -> new BukkitGiant(giant);
            case GlowSquid glowSquid -> new BukkitGlowSquid(glowSquid);
            case Goat goat -> new BukkitGoat(goat);
            case Guardian guardian -> new BukkitGuardian(guardian);
            case HappyGhast happyGhast -> new BukkitHappyGhast(happyGhast);
            case Hoglin hoglin -> new BukkitHoglin(hoglin);
            case Horse horse -> new BukkitHorse(horse);
            case Husk husk -> new BukkitHusk(husk);
            case Illusioner illusioner -> new BukkitIllusioner(illusioner);
            case IronGolem ironGolem -> new BukkitIronGolem(ironGolem);
            case TraderLlama traderLlama -> new BukkitTraderLlama(traderLlama);
            case Llama llama -> new BukkitLlama(llama);
            case MagmaCube magmaCube -> new BukkitMagmaCube(magmaCube);
            case Mule mule -> new BukkitMule(mule);
            case MushroomCow mushroomCow -> new BukkitMushroomCow(mushroomCow);
            case Nautilus nautilus -> new BukkitNautilus(nautilus);
            case Ocelot ocelot -> new BukkitOcelot(ocelot);
            case Panda panda -> new BukkitPanda(panda);
            case Parched parched -> new BukkitParched(parched);
            case Parrot parrot -> new BukkitParrot(parrot);
            case Phantom phantom -> new BukkitPhantom(phantom);
            case Pig pig -> new BukkitPig(pig);
            case Piglin piglin -> new BukkitPiglin(piglin);
            case PiglinBrute piglinBrute -> new BukkitPiglinBrute(piglinBrute);
            case PigZombie pigZombie -> new BukkitZombifiedPiglin(pigZombie);
            case Pillager pillager -> new BukkitPillager(pillager);
            case PolarBear polarBear -> new BukkitPolarBear(polarBear);
            case PufferFish pufferFish -> new BukkitPufferFish(pufferFish);
            case Rabbit rabbit -> new BukkitRabbit(rabbit);
            case Ravager ravager -> new BukkitRavager(ravager);
            case Salmon salmon -> new BukkitSalmon(salmon);
            case Sheep sheep -> new BukkitSheep(sheep);
            case Shulker shulker -> new BukkitShulker(shulker);
            case Silverfish silverfish -> new BukkitSilverfish(silverfish);
            case Skeleton skeleton -> new BukkitSkeleton(skeleton);
            case SkeletonHorse skeletonHorse -> new BukkitSkeletonHorse(skeletonHorse);
            case Slime slime -> new BukkitSlime(slime);
            case Sniffer sniffer -> new BukkitSniffer(sniffer);
            case Snowman snowman -> new BukkitSnowman(snowman);
            case Spider spider -> new BukkitSpider(spider);
            case Squid squid -> new BukkitSquid(squid);
            case Stray stray -> new BukkitStray(stray);
            case Strider strider -> new BukkitStrider(strider);
            case Tadpole tadpole -> new BukkitTadpole(tadpole);
            case TropicalFish tropicalFish -> new BukkitTropicalFish(tropicalFish);
            case Turtle turtle -> new BukkitTurtle(turtle);
            case Vex vex -> new BukkitVex(vex);
            case Villager villager -> new BukkitVillager(villager);
            case Vindicator vindicator -> new BukkitVindicator(vindicator);
            case WanderingTrader wanderingTrader -> new BukkitWanderingTrader(wanderingTrader);
            case Warden warden -> new BukkitWarden(warden);
            case Witch witch -> new BukkitWitch(witch);
            case Wither wither -> new BukkitWither(wither);
            case WitherSkeleton witherSkeleton -> new BukkitWitherSkeleton(witherSkeleton);
            case Wolf wolf -> new BukkitWolf(wolf);
            case Zoglin zoglin -> new BukkitZoglin(zoglin);
            case ZombieVillager zombieVillager -> new BukkitZombieVillager(zombieVillager);
            case Zombie zombie -> new BukkitZombie(zombie);
            case ZombieHorse zombieHorse -> new BukkitZombieHorse(zombieHorse);
            case ZombieNautilus zombieNautilus -> new BukkitZombieNautilus(zombieNautilus);
            default -> new BukkitUnknownMob(mob);
        };
    }
}
