package be.renaud11232.bluemapmobs;

import be.renaud11232.bluemapmobs.icon.Icon;
import be.renaud11232.bluemapmobs.icon.TextureIcon;
import be.renaud11232.bluemapmobs.icon.SimpleIcon;
import com.flowpowered.math.vector.Vector2i;
import org.bukkit.DyeColor;
import org.bukkit.entity.TropicalFish;

import java.io.IOException;
import java.nio.file.Path;

public final class BlueMapMobsIcon {
    public static final Icon UNKNOWN = new SimpleIcon("assets/bluemapmobs/img/unknown.png", new Vector2i(12, 12));
    public static final class Mob {
        public static final Icon BAT = new SimpleIcon("assets/bluemapmobs/img/mobs/ambient/bat.png", new Vector2i(12, 12));
        public static final Icon ALLAY = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/allay.png", new Vector2i(12, 12));
        public static final Icon CAMEL = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/camel.png", new Vector2i(12, 12));
        public static final Icon DONKEY = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/chestedhorse/donkey.png", new Vector2i(12, 12));
        public static final Icon LLAMA_EMPTY_DECOR = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/chestedhorse/llama/decor/empty.png", new Vector2i(12, 12));
        public static final Icon TRADER_LLAMA_DECOR = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/chestedhorse/llama/decor/trader_llama.png", new Vector2i(12, 12));
        public static final Icon WHITE_LLAMA_DECOR = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/chestedhorse/llama/decor/white.png", new Vector2i(12, 12));
        public static final Icon LIGHTGRAY_LLAMA_DECOR = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/chestedhorse/llama/decor/light_gray.png", new Vector2i(12, 12));
        public static final Icon GRAY_LLAMA_DECOR = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/chestedhorse/llama/decor/gray.png", new Vector2i(12, 12));
        public static final Icon BLACK_LLAMA_DECOR = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/chestedhorse/llama/decor/black.png", new Vector2i(12, 12));
        public static final Icon BROWN_LLAMA_DECOR = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/chestedhorse/llama/decor/brown.png", new Vector2i(12, 12));
        public static final Icon RED_LLAMA_DECOR = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/chestedhorse/llama/decor/red.png", new Vector2i(12, 12));
        public static final Icon ORANGE_LLAMA_DECOR = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/chestedhorse/llama/decor/orange.png", new Vector2i(12, 12));
        public static final Icon YELLOW_LLAMA_DECOR = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/chestedhorse/llama/decor/yellow.png", new Vector2i(12, 12));
        public static final Icon LIME_LLAMA_DECOR = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/chestedhorse/llama/decor/lime.png", new Vector2i(12, 12));
        public static final Icon GREEN_LLAMA_DECOR = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/chestedhorse/llama/decor/green.png", new Vector2i(12, 12));
        public static final Icon CYAN_LLAMA_DECOR = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/chestedhorse/llama/decor/cyan.png", new Vector2i(12, 12));
        public static final Icon LIGHTBLUE_LLAMA_DECOR = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/chestedhorse/llama/decor/light_blue.png", new Vector2i(12, 12));
        public static final Icon BLUE_LLAMA_DECOR = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/chestedhorse/llama/decor/blue.png", new Vector2i(12, 12));
        public static final Icon PURPLE_LLAMA_DECOR = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/chestedhorse/llama/decor/purple.png", new Vector2i(12, 12));
        public static final Icon MAGENTA_LLAMA_DECOR = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/chestedhorse/llama/decor/magenta.png", new Vector2i(12, 12));
        public static final Icon PINK_LLAMA_DECOR = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/chestedhorse/llama/decor/pink.png", new Vector2i(12, 12));
        public static final Icon MULE = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/chestedhorse/mule.png", new Vector2i(12, 12));
        public static final Icon HORSE_MARKINGS_NONE = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/horse/horse_markings_none.png", new Vector2i(12, 12));
        public static final Icon HORSE_MARKINGS_WHITE = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/horse/horse_markings_white.png", new Vector2i(12, 12));
        public static final Icon HORSE_MARKINGS_WHITEFIELD = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/horse/horse_markings_whitefield.png", new Vector2i(12, 12));
        public static final Icon HORSE_MARKINGS_WHITE_DOTS = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/horse/horse_markings_white_dots.png", new Vector2i(12, 12));
        public static final Icon HORSE_MARKINGS_BLACK_DOTS = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/horse/horse_markings_black_dots.png", new Vector2i(12, 12));
        public static final Icon SKELETON_HORSE = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/skeleton_horse.png", new Vector2i(12, 12));
        public static final Icon ZOMBIE_HORSE = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/zombie_horse.png", new Vector2i(12, 12));
        public static final Icon ARMADILLO = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/armadillo.png", new Vector2i(12, 12));
        public static final Icon LUCY_AXOLOTL = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/axolotl/lucy_axolotl.png", new Vector2i(12, 12));
        public static final Icon WILD_AXOLOTL = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/axolotl/wild_axolotl.png", new Vector2i(12, 12));
        public static final Icon GOLD_AXOLOTL = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/axolotl/gold_axolotl.png", new Vector2i(12, 12));
        public static final Icon CYAN_AXOLOTL = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/axolotl/cyan_axolotl.png", new Vector2i(12, 12));
        public static final Icon BLUE_AXOLOTL = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/axolotl/blue_axolotl.png", new Vector2i(12, 12));
        public static final Icon BEE = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/bee.png", new Vector2i(12, 12));
        public static final Icon ALL_BLACK_CAT = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/cat/all_black.png", new Vector2i(12, 12));
        public static final Icon BLACK_CAT = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/cat/black.png", new Vector2i(12, 12));
        public static final Icon BRITISH_SHORTHAIR_CAT = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/cat/british_shorthair.png", new Vector2i(12, 12));
        public static final Icon CALICO_CAT = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/cat/calico.png", new Vector2i(12, 12));
        public static final Icon JELLIE_CAT = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/cat/jellie.png", new Vector2i(12, 12));
        public static final Icon PERSIAN_CAT = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/cat/persian.png", new Vector2i(12, 12));
        public static final Icon RAGDOLL_CAT = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/cat/ragdoll.png", new Vector2i(12, 12));
        public static final Icon RED_CAT = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/cat/red.png", new Vector2i(12, 12));
        public static final Icon SIAMESE_CAT = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/cat/siamese.png", new Vector2i(12, 12));
        public static final Icon TABBY_CAT = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/cat/tabby.png", new Vector2i(12, 12));
        public static final Icon WHITE_CAT = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/cat/white.png", new Vector2i(12, 12));
        public static final Icon TEMPERATE_CHICKEN = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/chicken/temperate_chicken.png", new Vector2i(12, 12));
        public static final Icon COLD_CHICKEN = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/chicken/cold_chicken.png", new Vector2i(12, 12));
        public static final Icon WARM_CHICKEN = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/chicken/warm_chicken.png", new Vector2i(12, 12));
        public static final Icon TEMPERATE_COW = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/abstractcow/cow/temperate_cow.png", new Vector2i(12, 12));
        public static final Icon COLD_COW = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/abstractcow/cow/cold_cow.png", new Vector2i(12, 12));
        public static final Icon WARM_COW = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/abstractcow/cow/warm_cow.png", new Vector2i(12, 12));
        public static final Icon RED_MOOSHROOM = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/abstractcow/mooshroom/red_mooshroom.png", new Vector2i(12, 12));
        public static final Icon BROWN_MOOSHROOM = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/abstractcow/mooshroom/brown_mooshroom.png", new Vector2i(12, 12));
        public static final Icon RED_FOX = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/fox/red_fox.png", new Vector2i(12, 12));
        public static final Icon SNOW_FOX = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/fox/snow_fox.png", new Vector2i(12, 12));
        public static final Icon TEMPERATE_FROG = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/frog/temperate_frog.png", new Vector2i(12, 12));
        public static final Icon COLD_FROG = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/frog/cold_frog.png", new Vector2i(12, 12));
        public static final Icon TROPICAL_FROG = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/frog/tropical_frog.png", new Vector2i(12, 12));
        public static final Icon GOAT = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/goat.png", new Vector2i(12, 12));
        public static final Icon HAPPY_GHAST_NO_HARNESS = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/happy_ghast/no_harness.png", new Vector2i(12, 12));
        public static final Icon WHITE_HAPPY_GHAST_HARNESS = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/happy_ghast/white_harness.png", new Vector2i(12, 12));
        public static final Icon LIGHTGRAY_HAPPY_GHAST_HARNESS = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/happy_ghast/lightgray_harness.png", new Vector2i(12, 12));
        public static final Icon GRAY_HAPPY_GHAST_HARNESS = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/happy_ghast/gray_harness.png", new Vector2i(12, 12));
        public static final Icon BLACK_HAPPY_GHAST_HARNESS = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/happy_ghast/black_harness.png", new Vector2i(12, 12));
        public static final Icon BROWN_HAPPY_GHAST_HARNESS = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/happy_ghast/brown_harness.png", new Vector2i(12, 12));
        public static final Icon RED_HAPPY_GHAST_HARNESS = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/happy_ghast/red_harness.png", new Vector2i(12, 12));
        public static final Icon ORANGE_HAPPY_GHAST_HARNESS = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/happy_ghast/orange_harness.png", new Vector2i(12, 12));
        public static final Icon YELLOW_HAPPY_GHAST_HARNESS = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/happy_ghast/yellow_harness.png", new Vector2i(12, 12));
        public static final Icon LIME_HAPPY_GHAST_HARNESS = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/happy_ghast/lime_harness.png", new Vector2i(12, 12));
        public static final Icon GREEN_HAPPY_GHAST_HARNESS = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/happy_ghast/green_harness.png", new Vector2i(12, 12));
        public static final Icon CYAN_HAPPY_GHAST_HARNESS = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/happy_ghast/cyan_harness.png", new Vector2i(12, 12));
        public static final Icon LIGHTBLUE_HAPPY_GHAST_HARNESS = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/happy_ghast/lightblue_harness.png", new Vector2i(12, 12));
        public static final Icon BLUE_HAPPY_GHAST_HARNESS = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/happy_ghast/blue_harness.png", new Vector2i(12, 12));
        public static final Icon PURPLE_HAPPY_GHAST_HARNESS = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/happy_ghast/purple_harness.png", new Vector2i(12, 12));
        public static final Icon MAGENTA_HAPPY_GHAST_HARNESS = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/happy_ghast/magenta_harness.png", new Vector2i(12, 12));
        public static final Icon PINK_HAPPY_GHAST_HARNESS = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/happy_ghast/pink_harness.png", new Vector2i(12, 12));
        public static final Icon HOGLIN = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/hoglin.png", new Vector2i(12, 12));
        public static final Icon OCELOT = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/ocelot.png", new Vector2i(12, 12));
        public static final Icon NORMAL_PANDA = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/panda/normal_panda.png", new Vector2i(12, 12));
        public static final Icon LAZY_PANDA = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/panda/lazy_panda.png", new Vector2i(12, 12));
        public static final Icon WORRIED_PANDA = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/panda/worried_panda.png", new Vector2i(12, 12));
        public static final Icon PLAYFUL_PANDA = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/panda/playful_panda.png", new Vector2i(12, 12));
        public static final Icon AGGRESSIVE_PANDA = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/panda/aggressive_panda.png", new Vector2i(12, 12));
        public static final Icon WEAK_PANDA = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/panda/weak_panda.png", new Vector2i(12, 12));
        public static final Icon BROWN_PANDA = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/panda/brown_panda.png", new Vector2i(12, 12));
        public static final Icon RED_PARROT = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/parrot/red_parrot.png", new Vector2i(12, 12));
        public static final Icon BLUE_PARROT = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/parrot/blue_parrot.png", new Vector2i(12, 12));
        public static final Icon GREEN_PARROT = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/parrot/green_parrot.png", new Vector2i(12, 12));
        public static final Icon CYAN_PARROT = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/parrot/cyan_parrot.png", new Vector2i(12, 12));
        public static final Icon GRAY_PARROT = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/parrot/gray_parrot.png", new Vector2i(12, 12));
        public static final Icon TEMPERATE_PIG = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/pig/temperate_pig.png", new Vector2i(12, 12));
        public static final Icon COLD_PIG = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/pig/cold_pig.png", new Vector2i(12, 12));
        public static final Icon WARM_PIG = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/pig/warm_pig.png", new Vector2i(12, 12));
        public static final Icon POLAR_BEAR = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/polar_bear.png", new Vector2i(12, 12));
        public static final Icon BLACK_RABBIT = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/rabbit/black.png", new Vector2i(12, 12));
        public static final Icon BROWN_RABBIT = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/rabbit/brown.png", new Vector2i(12, 12));
        public static final Icon GOLD_RABBIT = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/rabbit/gold.png", new Vector2i(12, 12));
        public static final Icon SALT_RABBIT = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/rabbit/salt.png", new Vector2i(12, 12));
        public static final Icon WHITE_RABBIT = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/rabbit/white.png", new Vector2i(12, 12));
        public static final Icon WHITE_SPLOTCHED_RABBIT = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/rabbit/white_splotched.png", new Vector2i(12, 12));
        public static final Icon TOAST_RABBIT = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/rabbit/toast.png", new Vector2i(12, 12));
        public static final Icon CAERBANNOG_RABBIT = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/rabbit/caerbannog.png", new Vector2i(12, 12));
        public static final Icon SHEEP = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/sheep/sheep.png", new Vector2i(12, 12));
        public static final Icon SNIFFER = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/sniffer.png", new Vector2i(12, 12));
        public static final Icon STRIDER = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/strider.png", new Vector2i(12, 12));
        public static final Icon TURTLE = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/turtle.png", new Vector2i(12, 12));
        public static final Icon ANGRY_ASHEN_WOLF = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/wolf/angry_ashen.png", new Vector2i(12, 12));
        public static final Icon ANGRY_BLACK_WOLF = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/wolf/angry_black.png", new Vector2i(12, 12));
        public static final Icon ANGRY_CHESTNUT_WOLF = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/wolf/angry_chestnut.png", new Vector2i(12, 12));
        public static final Icon ANGRY_PALE_WOLF = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/wolf/angry_pale.png", new Vector2i(12, 12));
        public static final Icon ANGRY_RUSTY_WOLF = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/wolf/angry_rusty.png", new Vector2i(12, 12));
        public static final Icon ANGRY_SNOWY_WOLF = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/wolf/angry_snowy.png", new Vector2i(12, 12));
        public static final Icon ANGRY_SPOTTED_WOLF = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/wolf/angry_spotted.png", new Vector2i(12, 12));
        public static final Icon ANGRY_STRIPED_WOLF = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/wolf/angry_striped.png", new Vector2i(12, 12));
        public static final Icon ANGRY_WOODS_WOLF = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/wolf/angry_woods.png", new Vector2i(12, 12));
        public static final Icon UNTAMED_ASHEN_WOLF = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/wolf/untamed_ashen.png", new Vector2i(12, 12));
        public static final Icon UNTAMED_BLACK_WOLF = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/wolf/untamed_black.png", new Vector2i(12, 12));
        public static final Icon UNTAMED_CHESTNUT_WOLF = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/wolf/untamed_chestnut.png", new Vector2i(12, 12));
        public static final Icon UNTAMED_PALE_WOLF = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/wolf/untamed_pale.png", new Vector2i(12, 12));
        public static final Icon UNTAMED_RUSTY_WOLF = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/wolf/untamed_rusty.png", new Vector2i(12, 12));
        public static final Icon UNTAMED_SNOWY_WOLF = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/wolf/untamed_snowy.png", new Vector2i(12, 12));
        public static final Icon UNTAMED_SPOTTED_WOLF = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/wolf/untamed_spotted.png", new Vector2i(12, 12));
        public static final Icon UNTAMED_STRIPED_WOLF = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/wolf/untamed_striped.png", new Vector2i(12, 12));
        public static final Icon UNTAMED_WOODS_WOLF = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/wolf/untamed_woods.png", new Vector2i(12, 12));
        public static final Icon TAMED_ASHEN_WOLF = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/wolf/tamed_ashen.png", new Vector2i(12, 12));
        public static final Icon TAMED_BLACK_WOLF = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/wolf/tamed_black.png", new Vector2i(12, 12));
        public static final Icon TAMED_CHESTNUT_WOLF = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/wolf/tamed_chestnut.png", new Vector2i(12, 12));
        public static final Icon TAMED_PALE_WOLF = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/wolf/tamed_pale.png", new Vector2i(12, 12));
        public static final Icon TAMED_RUSTY_WOLF = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/wolf/tamed_rusty.png", new Vector2i(12, 12));
        public static final Icon TAMED_SNOWY_WOLF = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/wolf/tamed_snowy.png", new Vector2i(12, 12));
        public static final Icon TAMED_SPOTTED_WOLF = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/wolf/tamed_spotted.png", new Vector2i(12, 12));
        public static final Icon TAMED_STRIPED_WOLF = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/wolf/tamed_striped.png", new Vector2i(12, 12));
        public static final Icon TAMED_WOODS_WOLF = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/animals/wolf/tamed_woods.png", new Vector2i(12, 12));
        public static final Icon UNAFFECTED_COPPER_GOLEM = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/golem/copper_golem/unaffected.png", new Vector2i(12, 12));
        public static final Icon EXPOSED_COPPER_GOLEM = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/golem/copper_golem/exposed.png", new Vector2i(12, 12));
        public static final Icon WEATHERED_COPPER_GOLEM = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/golem/copper_golem/weathered.png", new Vector2i(12, 12));
        public static final Icon OXIDIZED_COPPER_GOLEM = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/golem/copper_golem/oxidized.png", new Vector2i(12, 12));
        public static final Icon IRON_GOLEM = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/golem/iron_golem.png", new Vector2i(12, 12));
        public static final Icon SHULKER = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/golem/shulker.png", new Vector2i(12, 12));
        public static final Icon NORMAL_SNOWMAN = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/golem/snowman/normal.png", new Vector2i(12, 12));
        public static final Icon DERP_SNOWMAN = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/golem/snowman/derp.png", new Vector2i(12, 12));
        public static final Icon BOGGED = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/abstractskeleton/bogged.png", new Vector2i(12, 12));
        public static final Icon SKELETON = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/abstractskeleton/skeleton.png", new Vector2i(12, 12));
        public static final Icon STRAY = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/abstractskeleton/stray.png", new Vector2i(12, 12));
        public static final Icon WITHER_SKELETON = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/abstractskeleton/wither_skeleton.png", new Vector2i(12, 12));
        public static final Icon BLAZE = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/blaze.png", new Vector2i(12, 12));
        public static final Icon BREEZE = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/breeze.png", new Vector2i(12, 12));
        public static final Icon CREAKING = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/creaking.png", new Vector2i(12, 12));
        public static final Icon CREEPER = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/creeper/creeper.png", new Vector2i(12, 12));
        public static final Icon CHARGED_CREEPER = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/creeper/charged_creeper.png", new Vector2i(12, 12));
        public static final Icon ENDERMAN = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/enderman.png", new Vector2i(12, 12));
        public static final Icon ENDERMITE = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/endermite.png", new Vector2i(12, 12));
        public static final Icon GIANT = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/giant.png", new Vector2i(12, 12));
        public static final Icon GUARDIAN = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/guardian/guardian.png", new Vector2i(12, 12));
        public static final Icon ELDER_GUARDIAN = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/guardian/elder_guardian.png", new Vector2i(12, 12));
        public static final Icon PIGLIN = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/piglinabstract/piglin.png", new Vector2i(12, 12));
        public static final Icon PIGLIN_BRUTE = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/piglinabstract/piglin_brute.png", new Vector2i(12, 12));
        public static final Icon PILLAGER = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/raider/illager/pillager.png", new Vector2i(12, 12));
        public static final Icon EVOKER = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/raider/illager/spellcaster/evoker.png", new Vector2i(12, 12));
        public static final Icon ILLUSIONER = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/raider/illager/spellcaster/illusioner.png", new Vector2i(12, 12));
        public static final Icon VINDICATOR = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/raider/illager/vindicator.png", new Vector2i(12, 12));
        public static final Icon RAVAGER = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/raider/ravager.png", new Vector2i(12, 12));
        public static final Icon WITCH = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/raider/witch.png", new Vector2i(12, 12));
        public static final Icon SILVERFISH = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/silverfish.png", new Vector2i(12, 12));
        public static final Icon SPIDER = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/spider/spider.png", new Vector2i(12, 12));
        public static final Icon CAVE_SPIDER = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/spider/cave_spider.png", new Vector2i(12, 12));
        public static final Icon VEX = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/vex.png", new Vector2i(12, 12));
        public static final Icon WARDEN = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/warden.png", new Vector2i(12, 12));
        public static final Icon WITHER = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/wither.png", new Vector2i(12, 12));
        public static final Icon ZOGLIN = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/zoglin.png", new Vector2i(12, 12));
        public static final Icon ZOMBIE = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/zombie/zombie.png", new Vector2i(12, 12));
        public static final Icon DROWNED = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/zombie/drowned.png", new Vector2i(12, 12));
        public static final Icon HUSK = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/zombie/husk.png", new Vector2i(12, 12));
        public static final Icon PIG_ZOMBIE = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/zombie/pig_zombie.png", new Vector2i(12, 12));
        public static final Icon DESERT_ZOMBIE_VILLAGER = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/zombie/zombie_villager/desert.png", new Vector2i(12, 12));
        public static final Icon JUNGLE_ZOMBIE_VILLAGER = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/zombie/zombie_villager/jungle.png", new Vector2i(12, 12));
        public static final Icon PLAINS_ZOMBIE_VILLAGER = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/zombie/zombie_villager/plains.png", new Vector2i(12, 12));
        public static final Icon SAVANNA_ZOMBIE_VILLAGER = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/zombie/zombie_villager/savanna.png", new Vector2i(12, 12));
        public static final Icon SNOWY_ZOMBIE_VILLAGER = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/zombie/zombie_villager/snowy.png", new Vector2i(12, 12));
        public static final Icon SWAMP_ZOMBIE_VILLAGER = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/zombie/zombie_villager/swamp.png", new Vector2i(12, 12));
        public static final Icon TAIGA_ZOMBIE_VILLAGER = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/monster/zombie/zombie_villager/taiga.png", new Vector2i(12, 12));
        public static final Icon DESERT_VILLAGER = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/npc/abstractvillager/villager/desert.png", new Vector2i(12, 12));
        public static final Icon JUNGLE_VILLAGER = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/npc/abstractvillager/villager/jungle.png", new Vector2i(12, 12));
        public static final Icon PLAINS_VILLAGER = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/npc/abstractvillager/villager/plains.png", new Vector2i(12, 12));
        public static final Icon SAVANNA_VILLAGER = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/npc/abstractvillager/villager/savanna.png", new Vector2i(12, 12));
        public static final Icon SNOWY_VILLAGER = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/npc/abstractvillager/villager/snowy.png", new Vector2i(12, 12));
        public static final Icon SWAMP_VILLAGER = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/npc/abstractvillager/villager/swamp.png", new Vector2i(12, 12));
        public static final Icon TAIGA_VILLAGER = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/npc/abstractvillager/villager/taiga.png", new Vector2i(12, 12));
        public static final Icon WANDERING_TRADER = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/npc/abstractvillager/wandering_trader.png", new Vector2i(12, 12));
        public static final Icon DOLPHIN = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/watermob/dolphin.png", new Vector2i(12, 12));
        public static final Icon COD = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/watermob/fish/cod.png", new Vector2i(12, 12));
        public static final Icon PUFFER_FISH = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/watermob/fish/puffer_fish.png", new Vector2i(12, 12));
        public static final Icon SALMON = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/watermob/fish/salmon.png", new Vector2i(12, 12));
        public static final Icon TADPOLE = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/watermob/fish/tadpole.png", new Vector2i(12, 12));
        public static final Icon SQUID = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/watermob/squid/squid.png", new Vector2i(12, 12));
        public static final Icon GLOW_SQUID = new SimpleIcon("assets/bluemapmobs/img/mobs/creature/watermob/squid/glow_squid.png", new Vector2i(12, 12));
        public static final Icon ENDER_DRAGON = new SimpleIcon("assets/bluemapmobs/img/mobs/ender_dragon.png", new Vector2i(12, 12));
        public static final Icon GHAST = new SimpleIcon("assets/bluemapmobs/img/mobs/flying/ghast.png", new Vector2i(12, 12));
        public static final Icon PHANTOM = new SimpleIcon("assets/bluemapmobs/img/mobs/flying/phantom.png", new Vector2i(12, 12));
        public static final Icon SLIME = new SimpleIcon("assets/bluemapmobs/img/mobs/slime/slime.png", new Vector2i(12, 12));
        public static final Icon MAGMA_CUBE = new SimpleIcon("assets/bluemapmobs/img/mobs/slime/magma_cube.png", new Vector2i(12, 12));
        public static Icon tropicalFishPattern(TropicalFish.Pattern pattern, DyeColor patternColor) {
            return new SimpleIcon(String.format("assets/bluemapmobs/img/mobs/creature/watermob/fish/tropical_fish/tropical_fish_pattern_%s_%s.png", pattern.name().toLowerCase(), patternColor.name().toLowerCase()), new Vector2i(12, 12));
        }
    }
    public static final class Vehicle {
        public static final Icon CHEST_MINECART = new SimpleIcon("assets/bluemapmobs/img/vehicles/minecart/chest_minecart.png", new Vector2i(12, 12));
        public static final Icon COMMAND_BLOCK_MINECART = new SimpleIcon("assets/bluemapmobs/img/vehicles/minecart/command_block_minecart.png", new Vector2i(12, 12));
        public static final Icon FURNACE_MINECART = new SimpleIcon("assets/bluemapmobs/img/vehicles/minecart/furnace_minecart.png", new Vector2i(12, 12));
        public static final Icon HOPPER_MINECART = new SimpleIcon("assets/bluemapmobs/img/vehicles/minecart/hopper_minecart.png", new Vector2i(12, 12));
        public static final Icon MINECART = new SimpleIcon("assets/bluemapmobs/img/vehicles/minecart/minecart.png", new Vector2i(12, 12));
        public static final Icon SPAWNER_MINECART = new SimpleIcon("assets/bluemapmobs/img/vehicles/minecart/spawner_minecart.png", new Vector2i(12, 12));
        public static final Icon TNT_MINECART = new SimpleIcon("assets/bluemapmobs/img/vehicles/minecart/tnt_minecart.png", new Vector2i(12, 12));
        public static final Icon ACACIA_BOAT = new SimpleIcon("assets/bluemapmobs/img/vehicles/boat/acacia_boat.png", new Vector2i(12, 12));
        public static final Icon ACACIA_CHEST_BOAT = new SimpleIcon("assets/bluemapmobs/img/vehicles/boat/acacia_chest_boat.png", new Vector2i(12, 12));
        public static final Icon BAMBOO_CHEST_RAFT = new SimpleIcon("assets/bluemapmobs/img/vehicles/boat/bamboo_chest_raft.png", new Vector2i(12, 12));
        public static final Icon BAMBOO_RAFT = new SimpleIcon("assets/bluemapmobs/img/vehicles/boat/bamboo_raft.png", new Vector2i(12, 12));
        public static final Icon BIRCH_BOAT = new SimpleIcon("assets/bluemapmobs/img/vehicles/boat/birch_boat.png", new Vector2i(12, 12));
        public static final Icon BIRCH_CHEST_BOAT = new SimpleIcon("assets/bluemapmobs/img/vehicles/boat/birch_chest_boat.png", new Vector2i(12, 12));
        public static final Icon CHERRY_BOAT = new SimpleIcon("assets/bluemapmobs/img/vehicles/boat/cherry_boat.png", new Vector2i(12, 12));
        public static final Icon CHERRY_CHEST_BOAT = new SimpleIcon("assets/bluemapmobs/img/vehicles/boat/cherry_chest_boat.png", new Vector2i(12, 12));
        public static final Icon DARK_OAK_BOAT = new SimpleIcon("assets/bluemapmobs/img/vehicles/boat/dark_oak_boat.png", new Vector2i(12, 12));
        public static final Icon DARK_OAK_CHEST_BOAT = new SimpleIcon("assets/bluemapmobs/img/vehicles/boat/dark_oak_chest_boat.png", new Vector2i(12, 12));
        public static final Icon JUNGLE_BOAT = new SimpleIcon("assets/bluemapmobs/img/vehicles/boat/jungle_boat.png", new Vector2i(12, 12));
        public static final Icon JUNGLE_CHEST_BOAT = new SimpleIcon("assets/bluemapmobs/img/vehicles/boat/jungle_chest_boat.png", new Vector2i(12, 12));
        public static final Icon MANGROVE_BOAT = new SimpleIcon("assets/bluemapmobs/img/vehicles/boat/mangrove_boat.png", new Vector2i(12, 12));
        public static final Icon MANGROVE_CHEST_BOAT = new SimpleIcon("assets/bluemapmobs/img/vehicles/boat/mangrove_chest_boat.png", new Vector2i(12, 12));
        public static final Icon OAK_BOAT = new SimpleIcon("assets/bluemapmobs/img/vehicles/boat/oak_boat.png", new Vector2i(12, 12));
        public static final Icon OAK_CHEST_BOAT = new SimpleIcon("assets/bluemapmobs/img/vehicles/boat/oak_chest_boat.png", new Vector2i(12, 12));
        public static final Icon SPRUCE_BOAT = new SimpleIcon("assets/bluemapmobs/img/vehicles/boat/spruce_boat.png", new Vector2i(12, 12));
        public static final Icon SPRUCE_CHEST_BOAT = new SimpleIcon("assets/bluemapmobs/img/vehicles/boat/spruce_chest_boat.png", new Vector2i(12, 12));
        public static final Icon PALE_OAK_BOAT = new SimpleIcon("assets/bluemapmobs/img/vehicles/boat/pale_oak_boat.png", new Vector2i(12, 12));
        public static final Icon PALE_OAK_CHEST_BOAT = new SimpleIcon("assets/bluemapmobs/img/vehicles/boat/pale_oak_chest_boat.png", new Vector2i(12, 12));
    }
    public static final class Other {
        public static final Icon ARMOR_STAND = new SimpleIcon("assets/bluemapmobs/img/others/livingentity/armor_stand.png", new Vector2i(12, 12));
        public static final Icon DEFAULT_MANNEQUIN = new SimpleIcon("assets/bluemapmobs/img/others/livingentity/mannequin/default.png", new Vector2i(12, 12));
    }
    public static final class NPC {
        public static final Icon ALEX = new SimpleIcon("assets/bluemapmobs/img/npc/alex.png", new Vector2i(12, 12));
        public static final Icon ARI = new SimpleIcon("assets/bluemapmobs/img/npc/ari.png", new Vector2i(12, 12));
        public static final Icon EFE = new SimpleIcon("assets/bluemapmobs/img/npc/efe.png", new Vector2i(12, 12));
        public static final Icon KAI = new SimpleIcon("assets/bluemapmobs/img/npc/kai.png", new Vector2i(12, 12));
        public static final Icon MAKENA = new SimpleIcon("assets/bluemapmobs/img/npc/makena.png", new Vector2i(12, 12));
        public static final Icon NOOR = new SimpleIcon("assets/bluemapmobs/img/npc/noor.png", new Vector2i(12, 12));
        public static final Icon STEVE = new SimpleIcon("assets/bluemapmobs/img/npc/steve.png", new Vector2i(12, 12));
        public static final Icon SUNNY = new SimpleIcon("assets/bluemapmobs/img/npc/sunny.png", new Vector2i(12, 12));
        public static final Icon ZURI = new SimpleIcon("assets/bluemapmobs/img/npc/zuri.png", new Vector2i(12, 12));
        public static Icon head(Path webroot, String texture) throws IOException {
            return new TextureIcon(webroot, texture, "assets/bluemapmobs/img/npc/texture/{id}.png", new Vector2i(12, 12));
        }
    }
}
