package be.renaud11232.bluemapmobs.markerbuilder;

import be.renaud11232.bluemapentities.BlueMapEntitiesAPI;
import be.renaud11232.bluemapentities.entity.UnknownEntity;
import be.renaud11232.bluemapentities.markerbuilder.EmptyMarkerBuilder;
import be.renaud11232.bluemapentities.markerbuilder.SimpleMarkerBuilder;
import be.renaud11232.bluemapmobs.entity.*;

public class MobsMarkerBuilder extends SimpleMarkerBuilder<Mob> {
    public MobsMarkerBuilder(BlueMapEntitiesAPI api) {
        super(api);
        register(Allay.class, new AllayMarkerBuilder(getAPI()));
        register(Armadillo.class, new ArmadilloMarkerBuilder(getAPI()));
        register(Axolotl.class, new AxolotlMarkerBuilder(getAPI()));
        register(Bat.class, new BatMarkerBuilder(getAPI()));
        register(Bee.class, new BeeMarkerBuilder(getAPI()));
        register(Blaze.class, new BlazeMarkerBuilder(getAPI()));
        register(Bogged.class, new BoggedMarkerBuilder(getAPI()));
        register(Breeze.class, new BreezeMarkerBuilder(getAPI()));
        register(Camel.class, new CamelMarkerBuilder(getAPI()));
        register(CamelHusk.class, new CamelHuskMarkerBuilder(getAPI()));
        register(Cat.class, new CatMarkerBuilder(getAPI()));
        register(CaveSpider.class, new CaveSpiderMarkerBuilder(getAPI()));
        register(Chicken.class, new ChickenMarkerBuilder(getAPI()));
        register(Cod.class, new CodMarkerBuilder(getAPI()));
        register(CopperGolem.class, new CopperGolemMarkerBuilder(getAPI()));
        register(Cow.class, new CowMarkerBuilder(getAPI()));
        register(Creaking.class, new CreakingMarkerBuilder(getAPI()));
        register(Creeper.class, new CreeperMarkerBuilder(getAPI()));
        register(Dolphin.class, new DolphinMarkerBuilder(getAPI()));
        register(Donkey.class, new DonkeyMarkerBuilder(getAPI()));
        register(Drowned.class, new DrownedMarkerBuilder(getAPI()));
        register(ElderGuardian.class, new ElderGuardianMarkerBuilder(getAPI()));
        register(Enderman.class, new EndermanMarkerBuilder(getAPI()));
        register(Endermite.class, new EndermiteMarkerBuilder(getAPI()));
        register(EnderDragon.class, new EnderDragonMarkerBuilder(getAPI()));
        register(Evoker.class, new EvokerMarkerBuilder(getAPI()));
        register(Fox.class, new FoxMarkerBuilder(getAPI()));
        register(Frog.class, new FrogMarkerBuilder(getAPI()));
        register(Ghast.class, new GhastMarkerBuilder(getAPI()));
        register(Giant.class, new GiantMarkerBuilder(getAPI()));
        register(GlowSquid.class, new GlowSquidMarkerBuilder(getAPI()));
        register(Goat.class, new GoatMarkerBuilder(getAPI()));
        register(Guardian.class, new GuardianMarkerBuilder(getAPI()));
        register(HappyGhast.class, new HappyGhastMarkerBuilder(getAPI()));
        register(Hoglin.class, new HoglinMarkerBuilder(getAPI()));
        register(Horse.class, new HorseMarkerBuilder(getAPI()));
        register(Husk.class, new HuskMarkerBuilder(getAPI()));
        register(Illusioner.class, new IllusionerMarkerBuilder(getAPI()));
        register(IronGolem.class, new IronGolemMarkerBuilder(getAPI()));
        register(Llama.class, new LlamaMarkerBuilder(getAPI()));
        register(MagmaCube.class, new MagmaCubeMarkerBuilder(getAPI()));
        register(Mule.class, new MuleMarkerBuilder(getAPI()));
        register(MushroomCow.class, new MushroomCowMarkerBuilder(getAPI()));
        register(Nautilus.class, new NautilusMarkerBuilder(getAPI()));
        register(Ocelot.class, new OcelotMarkerBuilder(getAPI()));
        register(Panda.class, new PandaMarkerBuilder(getAPI()));
        register(Parched.class, new ParchedMarkerBuilder(getAPI()));
        register(Parrot.class, new ParrotMarkerBuilder(getAPI()));
        register(Phantom.class, new PhantomMarkerBuilder(getAPI()));
        register(Pig.class, new PigMarkerBuilder(getAPI()));
        register(Piglin.class, new PiglinMarkerBuilder(getAPI()));
        register(PiglinBrute.class, new PiglinBruteMarkerBuilder(getAPI()));
        register(PigZombie.class, new PigZombieMarkerBuilder(getAPI()));
        register(Pillager.class, new PillagerMarkerBuilder(getAPI()));
        register(PolarBear.class, new PolarBearMarkerBuilder(getAPI()));
        register(PufferFish.class, new PufferFishMarkerBuilder(getAPI()));
        register(Rabbit.class, new RabbitMarkerBuilder(getAPI()));
        register(Ravager.class, new RavagerMarkerBuilder(getAPI()));
        register(Salmon.class, new SalmonMarkerBuilder(getAPI()));
        register(Sheep.class, new SheepMarkerBuilder(getAPI()));
        register(Shulker.class, new ShulkerMarkerBuilder(getAPI()));
        register(Silverfish.class, new SilverfishMarkerBuilder(getAPI()));
        register(Skeleton.class, new SkeletonMarkerBuilder(getAPI()));
        register(SkeletonHorse.class, new SkeletonHorseMarkerBuilder(getAPI()));
        register(Slime.class, new SlimeMarkerBuilder(getAPI()));
        register(Sniffer.class, new SnifferMarkerBuilder(getAPI()));
        register(Snowman.class, new SnowmanMarkerBuilder(getAPI()));
        register(Spider.class, new SpiderMarkerBuilder(getAPI()));
        register(Squid.class, new SquidMarkerBuilder(getAPI()));
        register(Stray.class, new StrayMarkerBuilder(getAPI()));
        register(Strider.class, new StriderMarkerBuilder(getAPI()));
        register(Tadpole.class, new TadpoleMarkerBuilder(getAPI()));
        register(TraderLlama.class, new TraderLlamaMarkerBuilder(getAPI()));
        register(TropicalFish.class, new TropicalFishMarkerBuilder(getAPI()));
        register(Turtle.class, new TurtleMarkerBuilder(getAPI()));
        register(Vex.class, new VexMarkerBuilder(getAPI()));
        register(Villager.class, new VillagerMarkerBuilder(getAPI()));
        register(Vindicator.class, new VindicatorMarkerBuilder(getAPI()));
        register(WanderingTrader.class, new WanderingTraderMarkerBuilder(getAPI()));
        register(Warden.class, new WardenMarkerBuilder(getAPI()));
        register(Witch.class, new WitchMarkerBuilder(getAPI()));
        register(Wither.class, new WitherMarkerBuilder(getAPI()));
        register(WitherSkeleton.class, new WitherSkeletonMarkerBuilder(getAPI()));
        register(Wolf.class, new WolfMarkerBuilder(getAPI()));
        register(Zoglin.class, new ZoglinMarkerBuilder(getAPI()));
        register(Zombie.class, new ZombieMarkerBuilder(getAPI()));
        register(ZombieHorse.class, new ZombieHorseMarkerBuilder(getAPI()));
        register(ZombieNautilus.class, new ZombieNautilusMarkerBuilder(getAPI()));
        register(ZombieVillager.class, new ZombieVillagerMarkerBuilder(getAPI()));

        register(UnknownEntity.class, new EmptyMarkerBuilder<>());
    }
}
