name: BlueMapEntities
version: '${version}'
main: be.renaud11232.bluemapentities.bukkit.BukkitBlueMapEntities
api-version: '${apiVersion}'
depend:
  - BlueMap
authors:
  - Renaud11232
description: '${description}'
website: '${website}'
