name: BlueMapMobs
version: '${version}'
main: be.renaud11232.bluemapmobs.paper.PaperBlueMapMobs
api-version: '${apiVersion}'
depend:
  - BlueMap
authors:
  - Renaud11232
description: '${description}'
website: '${website}'
