name: BlueMapMobs
version: '${project.version}'
main: be.renaud11232.bluemapmobs.paper.PaperBlueMapMobs
api-version: '${net.minecraft.target.version}'
depend:
  - BlueMapEntities
authors:
  - Renaud11232
description: '${project.description}'
website: '${project.url}'
