name: BlueMapCitizens
version: '${version}'
main: be.renaud11232.bluemapcitizens.bukkit.BlueMapCitizens
api-version: '${apiVersion}'
depend:
  - BlueMapEntities
  - Citizens
authors:
  - Renaud11232
description: '${description}'
website: '${website}'
