name: BlueMapOthers
version: '${version}'
main: be.renaud11232.bluemapothers.paper.PaperBlueMapOthers
api-version: '${apiVersion}'
depend:
  - BlueMap
authors:
  - Renaud11232
description: '${description}'
website: '${website}'
