package be.renaud11232.bluemapmobs;

import com.flowpowered.math.vector.Vector2i;

public enum Icon {
    UNKNOWN("assets/bluemapmobs/img/unknown.png", new Vector2i(12, 12)),

    CHEST_MINECART("assets/bluemapmobs/img/vehicles/minecart/chest_minecart.png", new Vector2i(12, 12)),
    COMMAND_BLOCK_MINECART("assets/bluemapmobs/img/vehicles/minecart/command_block_minecart.png", new Vector2i(12, 12)),
    FURNACE_MINECART("assets/bluemapmobs/img/vehicles/minecart/furnace_minecart.png", new Vector2i(12, 12)),
    HOPPER_MINECART("assets/bluemapmobs/img/vehicles/minecart/hopper_minecart.png", new Vector2i(12, 12)),
    MINECART("assets/bluemapmobs/img/vehicles/minecart/minecart.png", new Vector2i(12, 12)),
    SPAWNER_MINECART("assets/bluemapmobs/img/vehicles/minecart/spawner_minecart.png", new Vector2i(12, 12)),
    TNT_MINECART("assets/bluemapmobs/img/vehicles/minecart/tnt_minecart.png", new Vector2i(12, 12)),
    ACACIA_BOAT("assets/bluemapmobs/img/vehicles/boat/acacia_boat.png", new Vector2i(12, 12)),
    ACACIA_CHEST_BOAT("assets/bluemapmobs/img/vehicles/boat/acacia_chest_boat.png", new Vector2i(12, 12)),
    BAMBOO_CHEST_RAFT("assets/bluemapmobs/img/vehicles/boat/bamboo_chest_raft.png", new Vector2i(12, 12)),
    BAMBOO_RAFT("assets/bluemapmobs/img/vehicles/boat/bamboo_raft.png", new Vector2i(12, 12)),
    BIRCH_BOAT("assets/bluemapmobs/img/vehicles/boat/birch_boat.png", new Vector2i(12, 12)),
    BIRCH_CHEST_BOAT("assets/bluemapmobs/img/vehicles/boat/birch_chest_boat.png", new Vector2i(12, 12)),
    CHERRY_BOAT("assets/bluemapmobs/img/vehicles/boat/cherry_boat.png", new Vector2i(12, 12)),
    CHERRY_CHEST_BOAT("assets/bluemapmobs/img/vehicles/boat/cherry_chest_boat.png", new Vector2i(12, 12)),
    DARK_OAK_BOAT("assets/bluemapmobs/img/vehicles/boat/dark_oak_boat.png", new Vector2i(12, 12)),
    DARK_OAK_CHEST_BOAT("assets/bluemapmobs/img/vehicles/boat/dark_oak_chest_boat.png", new Vector2i(12, 12)),
    JUNGLE_BOAT("assets/bluemapmobs/img/vehicles/boat/jungle_boat.png", new Vector2i(12, 12)),
    JUNGLE_CHEST_BOAT("assets/bluemapmobs/img/vehicles/boat/jungle_chest_boat.png", new Vector2i(12, 12)),
    MANGROVE_BOAT("assets/bluemapmobs/img/vehicles/boat/mangrove_boat.png", new Vector2i(12, 12)),
    MANGROVE_CHEST_BOAT("assets/bluemapmobs/img/vehicles/boat/mangrove_chest_boat.png", new Vector2i(12, 12)),
    OAK_BOAT("assets/bluemapmobs/img/vehicles/boat/oak_boat.png", new Vector2i(12, 12)),
    OAK_CHEST_BOAT("assets/bluemapmobs/img/vehicles/boat/oak_chest_boat.png", new Vector2i(12, 12)),
    SPRUCE_BOAT("assets/bluemapmobs/img/vehicles/boat/spruce_boat.png", new Vector2i(12, 12)),
    SPRUCE_CHEST_BOAT("assets/bluemapmobs/img/vehicles/boat/spruce_chest_boat.png", new Vector2i(12, 12)),

    BAT("assets/bluemapmobs/img/mobs/ambient/bat.png", new Vector2i(12, 12)),
    ALLAY("assets/bluemapmobs/img/mobs/creature/allay.png", new Vector2i(12, 12)),
    CAMEL("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/camel.png", new Vector2i(12, 12)),
    DONKEY("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/chestedhorse/donkey.png", new Vector2i(12, 12)),
    //TODO carpet variants
    LLAMA_EMPTY_DECOR("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/chestedhorse/llama/decor/empty.png", new Vector2i(12, 12)),
    TRADER_LLAMA_DECOR("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/chestedhorse/llama/decor/trader_llama.png", new Vector2i(12, 12)),
    MULE("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/chestedhorse/mule.png", new Vector2i(12, 12)),
    //TODO horse colors
    HORSE("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/horse.png", new Vector2i(12, 12)),
    SKELETON_HORSE("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/skeleton_horse.png", new Vector2i(12, 12)),
    ZOMBIE_HORSE("assets/bluemapmobs/img/mobs/creature/animals/abstracthorse/zombie_horse.png", new Vector2i(12, 12)),
    LUCY_AXOLOTL("assets/bluemapmobs/img/mobs/creature/animals/axolotl/lucy_axolotl.png", new Vector2i(12, 12)),
    WILD_AXOLOTL("assets/bluemapmobs/img/mobs/creature/animals/axolotl/wild_axolotl.png", new Vector2i(12, 12)),
    GOLD_AXOLOTL("assets/bluemapmobs/img/mobs/creature/animals/axolotl/gold_axolotl.png", new Vector2i(12, 12)),
    CYAN_AXOLOTL("assets/bluemapmobs/img/mobs/creature/animals/axolotl/cyan_axolotl.png", new Vector2i(12, 12)),
    BLUE_AXOLOTL("assets/bluemapmobs/img/mobs/creature/animals/axolotl/blue_axolotl.png", new Vector2i(12, 12)),
    BEE("assets/bluemapmobs/img/mobs/creature/animals/bee.png", new Vector2i(12, 12)),
    CAT("assets/bluemapmobs/img/mobs/creature/animals/cat.png", new Vector2i(12, 12)),
    CHICKEN("assets/bluemapmobs/img/mobs/creature/animals/chicken.png", new Vector2i(12, 12)),
    COW("assets/bluemapmobs/img/mobs/creature/animals/cow/cow.png", new Vector2i(12, 12)),
    RED_MOOSHROOM("assets/bluemapmobs/img/mobs/creature/animals/cow/red_mooshroom.png", new Vector2i(12, 12)),
    BROWN_MOOSHROOM("assets/bluemapmobs/img/mobs/creature/animals/cow/brown_mooshroom.png", new Vector2i(12, 12)),
    RED_FOX("assets/bluemapmobs/img/mobs/creature/animals/fox/red_fox.png", new Vector2i(12, 12)),
    SNOW_FOX("assets/bluemapmobs/img/mobs/creature/animals/fox/snow_fox.png", new Vector2i(12, 12)),
    TEMPERATE_FROG("assets/bluemapmobs/img/mobs/creature/animals/frog/temperate_frog.png", new Vector2i(12, 12)),
    COLD_FROG("assets/bluemapmobs/img/mobs/creature/animals/frog/cold_frog.png", new Vector2i(12, 12)),
    TROPICAL_FROG("assets/bluemapmobs/img/mobs/creature/animals/frog/tropical_frog.png", new Vector2i(12, 12)),
    GOAT("assets/bluemapmobs/img/mobs/creature/animals/goat.png", new Vector2i(12, 12)),
    HOGLIN("assets/bluemapmobs/img/mobs/creature/animals/hoglin.png", new Vector2i(12, 12)),
    OCELOT("assets/bluemapmobs/img/mobs/creature/animals/ocelot.png", new Vector2i(12, 12)),
    NORMAL_PANDA("assets/bluemapmobs/img/mobs/creature/animals/panda/normal_panda.png", new Vector2i(12, 12)),
    LAZY_PANDA("assets/bluemapmobs/img/mobs/creature/animals/panda/lazy_panda.png", new Vector2i(12, 12)),
    WORRIED_PANDA("assets/bluemapmobs/img/mobs/creature/animals/panda/worried_panda.png", new Vector2i(12, 12)),
    PLAYFUL_PANDA("assets/bluemapmobs/img/mobs/creature/animals/panda/playful_panda.png", new Vector2i(12, 12)),
    AGGRESSIVE_PANDA("assets/bluemapmobs/img/mobs/creature/animals/panda/aggressive_panda.png", new Vector2i(12, 12)),
    WEAK_PANDA("assets/bluemapmobs/img/mobs/creature/animals/panda/weak_panda.png", new Vector2i(12, 12)),
    BROWN_PANDA("assets/bluemapmobs/img/mobs/creature/animals/panda/brown_panda.png", new Vector2i(12, 12)),
    RED_PARROT("assets/bluemapmobs/img/mobs/creature/animals/parrot/red_parrot.png", new Vector2i(12, 12)),
    BLUE_PARROT("assets/bluemapmobs/img/mobs/creature/animals/parrot/blue_parrot.png", new Vector2i(12, 12)),
    GREEN_PARROT("assets/bluemapmobs/img/mobs/creature/animals/parrot/green_parrot.png", new Vector2i(12, 12)),
    CYAN_PARROT("assets/bluemapmobs/img/mobs/creature/animals/parrot/cyan_parrot.png", new Vector2i(12, 12)),
    GRAY_PARROT("assets/bluemapmobs/img/mobs/creature/animals/parrot/gray_parrot.png", new Vector2i(12, 12)),
    PIG("assets/bluemapmobs/img/mobs/creature/animals/pig.png", new Vector2i(12, 12)),
    POLAR_BEAR("assets/bluemapmobs/img/mobs/creature/animals/polar_bear.png", new Vector2i(12, 12)),
    BLACK_RABBIT("assets/bluemapmobs/img/mobs/creature/animals/rabbit/black.png", new Vector2i(12, 12)),
    BROWN_RABBIT("assets/bluemapmobs/img/mobs/creature/animals/rabbit/brown.png", new Vector2i(12, 12)),
    GOLD_RABBIT("assets/bluemapmobs/img/mobs/creature/animals/rabbit/gold.png", new Vector2i(12, 12)),
    SALT_RABBIT("assets/bluemapmobs/img/mobs/creature/animals/rabbit/salt.png", new Vector2i(12, 12)),
    WHITE_RABBIT("assets/bluemapmobs/img/mobs/creature/animals/rabbit/white.png", new Vector2i(12, 12)),
    WHITE_SPLOTCHED_RABBIT("assets/bluemapmobs/img/mobs/creature/animals/rabbit/white_splotched.png", new Vector2i(12, 12)),
    TOAST_RABBIT("assets/bluemapmobs/img/mobs/creature/animals/rabbit/toast.png", new Vector2i(12, 12)),
    CAERBANNOG_RABBIT("assets/bluemapmobs/img/mobs/creature/animals/rabbit/caerbannog.png", new Vector2i(12, 12)),
    SHEEP("assets/bluemapmobs/img/mobs/creature/animals/sheep/sheep.png", new Vector2i(12, 12)),
    SNIFFER("assets/bluemapmobs/img/mobs/creature/animals/sniffer.png", new Vector2i(12, 12)),
    STRIDER("assets/bluemapmobs/img/mobs/creature/animals/strider.png", new Vector2i(12, 12)),
    TURTLE("assets/bluemapmobs/img/mobs/creature/animals/turtle.png", new Vector2i(12, 12)),
    UNTAMED_WOLF("assets/bluemapmobs/img/mobs/creature/animals/wolf/untamed_wolf.png", new Vector2i(12, 12)),
    TAMED_WOLF("assets/bluemapmobs/img/mobs/creature/animals/wolf/tamed_wolf.png", new Vector2i(12, 12)),
    IRON_GOLEM("assets/bluemapmobs/img/mobs/creature/golem/iron_golem.png", new Vector2i(12, 12)),
    SHULKER("assets/bluemapmobs/img/mobs/creature/golem/shulker.png", new Vector2i(12, 12)),
    SNOWMAN("assets/bluemapmobs/img/mobs/creature/golem/snowman.png", new Vector2i(12, 12)),
    SKELETON("assets/bluemapmobs/img/mobs/creature/monster/abstractskeleton/skeleton.png", new Vector2i(12, 12)),
    STRAY("assets/bluemapmobs/img/mobs/creature/monster/abstractskeleton/stray.png", new Vector2i(12, 12)),
    WITHER_SKELETON("assets/bluemapmobs/img/mobs/creature/monster/abstractskeleton/wither_skeleton.png", new Vector2i(12, 12)),
    BLAZE("assets/bluemapmobs/img/mobs/creature/monster/blaze.png", new Vector2i(12, 12)),
    BREEZE("assets/bluemapmobs/img/mobs/creature/monster/breeze.png", new Vector2i(12, 12)),
    CREEPER("assets/bluemapmobs/img/mobs/creature/monster/creeper.png", new Vector2i(12, 12)),
    ENDERMAN("assets/bluemapmobs/img/mobs/creature/monster/enderman.png", new Vector2i(12, 12)),
    ENDERMITE("assets/bluemapmobs/img/mobs/creature/monster/endermite.png", new Vector2i(12, 12)),
    GIANT("assets/bluemapmobs/img/mobs/creature/monster/giant.png", new Vector2i(12, 12)),
    GUARDIAN("assets/bluemapmobs/img/mobs/creature/monster/guardian/guardian.png", new Vector2i(12, 12)),
    ELDER_GUARDIAN("assets/bluemapmobs/img/mobs/creature/monster/guardian/elder_guardian.png", new Vector2i(12, 12)),
    PIGLIN("assets/bluemapmobs/img/mobs/creature/monster/piglinabstract/piglin.png", new Vector2i(12, 12)),
    PIGLIN_BRUTE("assets/bluemapmobs/img/mobs/creature/monster/piglinabstract/piglin_brute.png", new Vector2i(12, 12)),
    PILLAGER("assets/bluemapmobs/img/mobs/creature/monster/raider/illager/pillager.png", new Vector2i(12, 12)),
    EVOKER("assets/bluemapmobs/img/mobs/creature/monster/raider/illager/spellcaster/evoker.png", new Vector2i(12, 12)),
    ILLUSIONER("assets/bluemapmobs/img/mobs/creature/monster/raider/illager/spellcaster/illusioner.png", new Vector2i(12, 12)),
    VINDICATOR("assets/bluemapmobs/img/mobs/creature/monster/raider/illager/vindicator.png", new Vector2i(12, 12)),
    RAVAGER("assets/bluemapmobs/img/mobs/creature/monster/raider/ravager.png", new Vector2i(12, 12)),
    WITCH("assets/bluemapmobs/img/mobs/creature/monster/raider/witch.png", new Vector2i(12, 12)),
    SILVERFISH("assets/bluemapmobs/img/mobs/creature/monster/silverfish.png", new Vector2i(12, 12)),
    SPIDER("assets/bluemapmobs/img/mobs/creature/monster/spider/spider.png", new Vector2i(12, 12)),
    CAVE_SPIDER("assets/bluemapmobs/img/mobs/creature/monster/spider/cave_spider.png", new Vector2i(12, 12)),
    VEX("assets/bluemapmobs/img/mobs/creature/monster/vex.png", new Vector2i(12, 12)),
    WARDEN("assets/bluemapmobs/img/mobs/creature/monster/warden.png", new Vector2i(12, 12)),
    WITHER("assets/bluemapmobs/img/mobs/creature/monster/wither.png", new Vector2i(12, 12)),
    ZOGLIN("assets/bluemapmobs/img/mobs/creature/monster/zoglin.png", new Vector2i(12, 12)),
    ZOMBIE("assets/bluemapmobs/img/mobs/creature/monster/zombie/zombie.png", new Vector2i(12, 12)),
    DROWNED("assets/bluemapmobs/img/mobs/creature/monster/zombie/drowned.png", new Vector2i(12, 12)),
    HUSK("assets/bluemapmobs/img/mobs/creature/monster/zombie/husk.png", new Vector2i(12, 12)),
    PIG_ZOMBIE("assets/bluemapmobs/img/mobs/creature/monster/zombie/pig_zombie.png", new Vector2i(12, 12)),
    //TODO Job variants ?
    ZOMBIE_VILLAGER("assets/bluemapmobs/img/mobs/creature/monster/zombie/zombie_villager.png", new Vector2i(12, 12)),
    //TODO Jobs variants ?
    VILLAGER("assets/bluemapmobs/img/mobs/creature/npc/abstractvillager/villager.png", new Vector2i(12, 12)),
    WANDERING_TRADER("assets/bluemapmobs/img/mobs/creature/npc/abstractvillager/wandering_trader.png", new Vector2i(12, 12)),
    DOLPHIN("assets/bluemapmobs/img/mobs/creature/watermob/dolphin.png", new Vector2i(12, 12)),
    COD("assets/bluemapmobs/img/mobs/creature/watermob/fish/cod.png", new Vector2i(12, 12)),
    PUFFER_FISH("assets/bluemapmobs/img/mobs/creature/watermob/fish/puffer_fish.png", new Vector2i(12, 12)),
    SALMON("assets/bluemapmobs/img/mobs/creature/watermob/fish/salmon.png", new Vector2i(12, 12)),
    TADPOLE("assets/bluemapmobs/img/mobs/creature/watermob/fish/tadpole.png", new Vector2i(12, 12)),
    //TODO variants & colors
    TROPICAL_FISH("assets/bluemapmobs/img/mobs/creature/watermob/fish/tropical_fish.png", new Vector2i(12, 12)),
    SQUID("assets/bluemapmobs/img/mobs/creature/watermob/squid/squid.png", new Vector2i(12, 12)),
    GLOW_SQUID("assets/bluemapmobs/img/mobs/creature/watermob/squid/glow_squid.png", new Vector2i(12, 12)),
    ENDER_DRAGON("assets/bluemapmobs/img/mobs/ender_dragon.png", new Vector2i(12, 12)),
    GHAST("assets/bluemapmobs/img/mobs/flying/ghast.png", new Vector2i(12, 12)),
    PHANTOM("assets/bluemapmobs/img/mobs/flying/phantom.png", new Vector2i(12, 12)),
    SLIME("assets/bluemapmobs/img/mobs/slime/slime.png", new Vector2i(12, 12)),
    MAGMA_CUBE("assets/bluemapmobs/img/mobs/slime/magma_cube.png", new Vector2i(12, 12));

    private final String path;
    private final Vector2i anchor;

    Icon(String path, Vector2i anchor) {
        this.path = path;
        this.anchor = anchor;
    }

    public String getPath() {
        return path;
    }

    public Vector2i getAnchor() {
        return anchor;
    }

}
